### ISSUE TITLE
Start JShell in Eclipse Terminal Not working!

### ISSUE THREAD

**Issue by LSW1980** [nileshkhaire/QuickShell#1]
Terminal tab appear  but did not connect to JShell - [JShell console like you show did not display... just blank tab]
[ OS: Windows 10 ]
[ Eclipse Platform - try both JShell.exe of jdk-9.0.4 and jdk-12.0.1  ==> still not working 
Version: 2019-12 (4.14)
Build id: I20191210-0610 ]

**Comment by nileshkhaire** [comment]
Hello @LSW1980 ,

Thank you for using QuickShell and creating first issue  :+1: 

I tried with Eclipse 2019-12 (4.14) and JDK 11 but it is not reproducible. 

Is it possible to start JShell executable ? (2nd command in QuickShell).

Could you please try following things: 

- Once terminal is opened, click on it and enter once. It may start a JShell console.
- Tried to start JShell.exe by double clicking on it and see if you can start it .

QuickShell is just opening executable in Eclipse terminal , so technically you can pass any shell program like python.exe , git-cmd.exe etc in QuickShell setting.

Check if you can start above shell successfully using QuickShell. If it is possible then it may be problem with your jshell .

I will also recommend to check with another Eclipse version. 

Let me know your findings :)

**Comment by LSW1980** [comment]
Thank you for the respond... After reading your msg, it dawned on me that I use a minimalist Eclipse that may not include terminal.
After install TM terminal, Jshell terminal console start working. (I found 3 terminal plug-ins. I just pick TM terminal, which one you use for your app?)
Great job on QuickShell ... Keep up the good work!
