### ISSUE TITLE
Quick Shell Configuration problem

### ISSUE THREAD

**Issue by seschneider58** [nileshkhaire/QuickShell#5]
I've followed the directions on GitHub to install the Quick Shell plugin. The plugin seems to have installed correctly and I was able to configure it according to the directions on GitHub. If I highlight a piece of java code and right click the drop down appears and I select run as Jshell script I Get the following error :

Can't execute script C:\Users\sesch\eclipse\java-2022-12\eclipse\.QuickShellTempDir\JShellScript.jsh (The system cannot find the path specified)

Can anyone assist me with a solution or a link to a KB article?
Thanks

**Comment by nileshkhaire** [comment]
Hello @seschneider58 Did you set QuickShell working directory? It is in eclipse preferences and after 'Select Jshell Executable' setting. 
Please set it and try again, if it is not working even though you have set it, please attach screenshot in the comment. 

Can you also check if file is created on this path : C:\Users\sesch\eclipse\java-2022-12\eclipse.QuickShellTempDir ? 

Thanks.

**Comment by seschneider58** [comment]
Nilesh,
 The  \eclipse.QuickShellTempDir\ subdirectory did not exist. I created a new folder in C:\Users\sesch\eclipse\java-2022-12\ and specified that in the Quick Shell preferences. That seems to have solved the problem. Since the folder was not created when I installed the plugin will I have to manually clean it up? It does not cause an error when I execute the jshell script twice it appears  to overwrite the file in the temp directory avoiding a duplicate filename error
Thanks for the guidance 
Steve

**Comment by nileshkhaire** [comment]
@seschneider58 Yes it will overwrite the file and that is as design. 

Unfortunately yes you have to clean the directory manually. But it will be just this one file only and nothing else. It is like temporary file and you can delete it any time.

Thanks for using QuickShell .
